# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8035f8bab50fbc4cdc8876936c9826ff5799cadc910a9dd408967170d56e9e2c747d560acbc61c654bbbdebcd9daac3ad744edba3c5f4b55bb588295c3fc6a5

test:
  secret_key_base: 4de87eebb2564514a732d24ad638a923cd81147283ad0bf1b7f968b979c7d9f66a3463aa56d753d0db10b4e2e5f7a0bb64e13a6d03008fbbcdf817f9c1e08f1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
